import Phaser from "phaser";
import { COLORS, PLAYER_SPEED } from "../utils/Constants";

export type Direction = "up" | "down" | "left" | "right";

// player-sheet: 16 frames (4 dirs × 4 walk frames) at 24×32 each
const FRAME_W = 24;
const FRAME_H = 32;

export class Player extends Phaser.GameObjects.Container {
  private sprite!: Phaser.GameObjects.Sprite;
  private shadowEllipse!: Phaser.GameObjects.Ellipse;
  private glowCircle!: Phaser.GameObjects.Arc;
  private _moveUp = false;
  private _moveDown = false;
  private _moveLeft = false;
  private _moveRight = false;
  private direction: Direction = "down";
  private _isMoving = false;
  private bobTimer = 0;

  declare body: Phaser.Physics.Arcade.Body;

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y);

    // Shadow and glow radii scaled up proportionally to match the 1.6× sprite
    this.shadowEllipse = scene.add.ellipse(0, 22, 26, 8, 0x000000, 0.3);
    this.add(this.shadowEllipse);

    this.glowCircle = scene.add.arc(
      0,
      2,
      29,
      0,
      360,
      false,
      COLORS.NEON_GREEN,
      0,
    );
    this.glowCircle.setStrokeStyle(2, COLORS.NEON_GREEN, 0.2);
    this.add(this.glowCircle);

    // Build spritesheet from the generated "player-sheet" texture
    this.ensureSpritesheet(scene);

    this.sprite = scene.add.sprite(0, 2, "player-sheet-anim", 0);
    this.sprite.setOrigin(0.5, 0.5);
    // Scale sprite 1.6× so the character is visibly larger relative to NPCs
    this.sprite.setScale(1.6);
    this.add(this.sprite);

    this.createAnimations(scene);

    scene.add.existing(this);
    scene.physics.add.existing(this);

    if (this.body) {
      // Physics body scaled to match the 1.6× visual — ~1.6× original 16×14/offset -8,4
      this.body.setSize(26, 22);
      this.body.setOffset(-13, 6);
      this.body.setMaxVelocity(PLAYER_SPEED, PLAYER_SPEED);
      this.body.setCollideWorldBounds(true);
    }

    this.setDepth(10);
    this.sprite.play("walk-down-idle");
  }

  private ensureSpritesheet(scene: Phaser.Scene): void {
    if (scene.textures.exists("player-sheet-anim")) return;
    // The "player-sheet" texture was generated by AssetGenerator at 384×32 (16 frames × 24px)
    // Copy it as a spritesheet under a new key with frame config
    const srcTex = scene.textures.get("player-sheet");
    // Build a canvas from the source texture, register as spritesheet
    const src = srcTex.getSourceImage();
    const canvas = document.createElement("canvas");
    const totalW = FRAME_W * 16;
    canvas.width = totalW;
    canvas.height = FRAME_H;
    const ctx = canvas.getContext("2d");
    if (ctx) ctx.drawImage(src as CanvasImageSource, 0, 0);
    scene.textures.addCanvas("player-sheet-anim", canvas);
    // Force spritesheet frame config
    scene.textures
      .get("player-sheet-anim")
      .add("__BASE", 0, 0, 0, totalW, FRAME_H);
    // Add individual frames
    for (let f = 0; f < 16; f++) {
      scene.textures
        .get("player-sheet-anim")
        .add(f, 0, f * FRAME_W, 0, FRAME_W, FRAME_H);
    }
  }

  private createAnimations(scene: Phaser.Scene): void {
    if (scene.anims.exists("walk-down")) return;

    const dirs: { key: string; row: number }[] = [
      { key: "down", row: 0 },
      { key: "up", row: 1 },
      { key: "left", row: 2 },
      { key: "right", row: 3 },
    ];

    for (const dir of dirs) {
      const base = dir.row * 4;
      scene.anims.create({
        key: `walk-${dir.key}`,
        frames: [
          { key: "player-sheet-anim", frame: base },
          { key: "player-sheet-anim", frame: base + 1 },
          { key: "player-sheet-anim", frame: base + 2 },
          { key: "player-sheet-anim", frame: base + 3 },
        ],
        frameRate: 8,
        repeat: -1,
      });
      scene.anims.create({
        key: `walk-${dir.key}-idle`,
        frames: [{ key: "player-sheet-anim", frame: base }],
        frameRate: 1,
        repeat: -1,
      });
    }
  }

  setMoveUp(v: boolean) {
    this._moveUp = v;
  }
  setMoveDown(v: boolean) {
    this._moveDown = v;
  }
  setMoveLeft(v: boolean) {
    this._moveLeft = v;
  }
  setMoveRight(v: boolean) {
    this._moveRight = v;
  }

  update(delta: number): void {
    if (!this.body) return;

    const vx = (this._moveRight ? 1 : 0) - (this._moveLeft ? 1 : 0);
    const vy = (this._moveDown ? 1 : 0) - (this._moveUp ? 1 : 0);
    const len = Math.sqrt(vx * vx + vy * vy);
    const nx = len > 0 ? (vx / len) * PLAYER_SPEED : 0;
    const ny = len > 0 ? (vy / len) * PLAYER_SPEED : 0;

    this.body.setVelocity(nx, ny);
    this._isMoving = nx !== 0 || ny !== 0;

    if (vx > 0) this.direction = "right";
    else if (vx < 0) this.direction = "left";
    else if (vy < 0) this.direction = "up";
    else if (vy > 0) this.direction = "down";

    const animKey = this._isMoving
      ? `walk-${this.direction}`
      : `walk-${this.direction}-idle`;
    if (this.sprite.anims.currentAnim?.key !== animKey) {
      this.sprite.play(animKey);
    }

    if (!this._isMoving) {
      this.bobTimer += delta;
      const bob = Math.sin(this.bobTimer / 300) * 0.8;
      this.sprite.setY(2 + bob);
    } else {
      this.bobTimer = 0;
      this.sprite.setY(2);
    }

    const pulseAlpha = 0.12 + Math.sin(Date.now() / 700) * 0.06;
    this.glowCircle.setAlpha(pulseAlpha);
    this.shadowEllipse.setAlpha(this._isMoving ? 0.35 : 0.25);
  }

  getDirection(): Direction {
    return this.direction;
  }
  getIsMoving(): boolean {
    return this._isMoving;
  }
}
