/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FileReference { 'hash' : string, 'path' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addXP' : ActorMethod<[string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAcceptedSuggestions' : ActorMethod<[], Array<[string, string]>>,
  'getAgentResults' : ActorMethod<[], Array<[Principal, string]>>,
  'getApiKey' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerLevel' : ActorMethod<[string], bigint>,
  'getCoverLetterFeedbackSessions' : ActorMethod<[], Array<[string, string]>>,
  'getCoverLetters' : ActorMethod<[], Array<[string, string]>>,
  'getExportNotes' : ActorMethod<[], Array<[string, string]>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getFlashcardSets' : ActorMethod<[], Array<[string, string]>>,
  'getInterviewFeedback' : ActorMethod<[], Array<[string, string]>>,
  'getResumeProfiles' : ActorMethod<[], Array<[string, string]>>,
  'getUserNotes' : ActorMethod<[], Array<[string, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkflowState' : ActorMethod<[], [] | [string]>,
  'getXP' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'saveAcceptedSuggestion' : ActorMethod<[string, string], undefined>,
  'saveAgentResult' : ActorMethod<[string, string], undefined>,
  'saveApiKey' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCoverLetter' : ActorMethod<[string, string], undefined>,
  'saveCoverLetterFeedbackSession' : ActorMethod<[string, string], undefined>,
  'saveExportNote' : ActorMethod<[string, string], undefined>,
  'saveFlashcardSet' : ActorMethod<[string, string], undefined>,
  'saveResumeProfile' : ActorMethod<[string, string], undefined>,
  'saveWorkflowState' : ActorMethod<[string], undefined>,
  'saveXP' : ActorMethod<[string, bigint], undefined>,
  'submitInterviewFeedback' : ActorMethod<[string, string], undefined>,
  'submitUserNote' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];